### ISSUE TITLE
`only` and `except` options

### ISSUE THREAD

**Issue by phated** [solidstate-network/hardhat-4byte-uploader#2]
Looking into adding this plugin into Dark Forest for my diamond work. Was wondering if you'd consider adding `only` and `except` options like your other plugins.

**Comment by ItsNickBarry** [comment]
I don't see any reason to exclude selectors from upload.  If they're already in the database, no change will be made.  If they're not in the database, they might as well be added.

**Comment by phated** [comment]
Not really worried about duplication. For example, if you deploy a series of contracts with 1 hardhat config, and some of them you don't want to be published at all.

**Comment by ItsNickBarry** [comment]
But why wouldn't you want some selectors to be published?  The only reason I can think of would be some sort of security-through-obscurity scheme.

**Comment by phated** [comment]
🤷‍♂️ I just try to think of the different scenarios people are going to throw at me. Haha

**Comment by ItsNickBarry** [comment]
I'll decline to add this for now, but we'll revisit if someone complains.
