### ISSUE TITLE
Print Function and Event selectors and signatures

### ISSUE THREAD

**Issue by 0xCourtney** [solidstate-network/hardhat-4byte-uploader#4]
Currently, this tool only uploads the function and event selectors to 4byte.directory. I propose we add some print functionality to this plugin such that the user can view the selectors and signatures for each contract in a table or list format.

**Comment by ItsNickBarry** [comment]
I looked into this, and now remember that the plugin doesn't calculate selectors at all.  Rather, it creates a fake composite ABI by combining all of the ABIs in the `artifacts/` directory, and uploads that to 4byte.directory.  The website handles the selector calculation.

So there's no technical reason to include this feature in this plugin.  No code can be shared.  However, I would like to add this functionality in some capacity - perhaps to the WIP diamond plugin?  Maybe even to ABI exporter?

Closing this issue, but open to discussion either here or in a separate chat.
